### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by OniBait** [CCM-Modding/Death-Timer#16]
http://pastebin.com/1nw6Viqc

Note: Server is running MCPC+ and I am a contributor, but it looks like this would/should happen any time EventTracker.ChuncksToTrackMap has more than one death being tracked _and_ is not the last death _and_ the person dies again.

This is due to you modifying the MultiMap within the iterator -- you either need to use Iterator.remove or add these entries to a list and remove them after you have iterated (or else add a break; statement -- might be the simplest solution).

I could send you a pull request if you wanted. But this code would probably work:

```
Iterables.removeIf(chunksToTrackMap.entries(), new Predicate<Entry<Long,DeathTimer>>() {
    @Override
    public boolean apply(@Nullable Entry<Long,DeathTimer> entry) {
        return entry != null && entry.getValue().username.equals(e.entityPlayer.username);
    }
});
```

This ends up calling remove on the iterator which works for concurrent modifications.

**Comment by dries007** [comment]
Thanks, I will implement when I get my dev thing setup again
