### ISSUE TITLE
This needs 1.6.2 updating.

### ISSUE THREAD

**Issue by Claycorp** [CCM-Modding/Death-Timer#18]
Yah c'mon dries mined getting this done :P?

**Comment by dries007** [comment]
Le sigh, if i don't fall asleep when I get home and I remember, i'll get on it.

**Comment by CaptainShadows** [comment]
I'll try to when I get home :-P

I need to do something to Nucleum anyway

**Comment by Claycorp** [comment]
There is no rush on the 1.6.2 preferably done by next week. (Bug Fixes and updates)

**Comment by dries007** [comment]
Will have to be delayed. There are some bugs reported to me we should probably fix first.
(Dimensions are not displayed correctly, example: Die in Mystcraft age 12 and it says dim 0 on screen)

**Comment by dries007** [comment]
Done.
